apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-fuse
  annotations:
    container.apparmor.security.beta.kubernetes.io/test-fuse: localhost/docker-fuse 
spec:
  selector:
    matchLabels:
      name: test-fuse
  template:
    metadata:
      labels:
        name: test-fuse
    spec:
      containers:
      - image: debian
        name: test-fuse
        command:
          - /bin/bash
          - -c
          - tail -f /dev/null
        resources:
          limits:
            github.com/fuse: "1"
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN

      tolerations:
        - operator: Exists
          effect: NoSchedule